apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-2.fullname" . }}-cm
data:
{{- if and .Values.lightrun .Values.lightrun.enable }}
  PRODUCTION_DEBUGGER: "true"
  LIGHTRUN_SECRET: {{ .Values.lightrun.secret }}
  LIGHTRUN_API_ENDPOINT: {{ .Values.lightrun.api_endpoint }}
  LIGHTRUN_PINNEDCERTS: {{ .Values.lightrun.pinned_cert }}
  LIGHTRUN_CA_PATH: {{ .Values.lightrun.ca_path }}
{{- end }}
  NODE_ENV: "production"
  ELASTIC_HOST: "http://{{ .Values.endpoints.elasticsearch }}"
  ELASTIC_INDEX_PATTERN: {{ .Values.elasticsearch.indexPattern}}
  SEARCH_ENTITY_TRANSFORMED_TOPIC: {{ .Values.searchEntityTransformedTopic }}
  SEARCH_SERVICE_GROUP_ID: {{ .Values.groupId }}
  KAFKA_BROKER: {{ .Values.endpoints.kafka }}
  KAFKA_BROKERS: {{ .Values.endpoints.kafkaBrokers }}
  KEY_PATH: {{ .Values.filePaths.kafkaSslKey }}
  CERT_PATH: {{ .Values.filePaths.kafkaSslCert }}
          
