apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-3.fullname" . }}-cm
data:
{{- if and .Values.lightrun .Values.lightrun.enable }}
  PRODUCTION_DEBUGGER: "true"
  LIGHTRUN_SECRET: {{ .Values.lightrun.secret }}
  LIGHTRUN_API_ENDPOINT: {{ .Values.lightrun.api_endpoint }}
  LIGHTRUN_PINNEDCERTS: {{ .Values.lightrun.pinned_cert }}
  LIGHTRUN_CA_PATH: {{ .Values.lightrun.ca_path }}
{{- end }}    
  KAFKA_BROKER: {{ .Values.endpoints.kafka }}
  KAFKA_BROKERS: {{ .Values.endpoints.kafkaBrokers }}
  KEY_PATH: {{ .Values.filePaths.kafkaSslKey }}
  CERT_PATH: {{ .Values.filePaths.kafkaSslCert }}
  DRONAMIC_OVERRIDE_TIME: {{ .Values.overrides.overrideDroneTime | quote }}
  DRONAMIC_OVERRIDE_DRONE_TYPE: {{ .Values.overrides.overrideDroneType | quote }}
  REDISDB_ENDPOINT: {{ .Values.endpoints.redisdb }}
