apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "service-3.fullname" . }}-list-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  {{ include "service-3.fullname" . }}-list-pods
subjects:
- kind: ServiceAccount
  name:  {{ include "service-3.serviceAccountName" . }}