apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
  labels:
    {{- include "service-3.labels" . | nindent 4 }}
  name: {{ include "service-3.fullname" . }}-list-pods
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list