apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-3.fullname" . }}
  labels:
    {{- include "service-3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if (eq "NodePort" .Values.service.type) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "service-3.selectorLabels" . | nindent 4 }}
